### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by BePasquet** [matthewnau/libmoji#14]
Hi first of all the library is amazing and is really powerfull what you can do combining the assets. My question is can be use on a live site our application wants to generate stickers for customers the thing is a preview url like this: https://preview.bitmoji.com/avatar-builder-v3/preview/fashion?scale=3&gender=1&style=5&rotation=0&beard=1638&brow=1538&cheek_details=-1&ear=1425&eye=1622&eyelash=2279&eye_details=1349&face_lines=1361&glasses=2389&hair=1692&hat=2544&jaw=1397&mouth=2338&nose=1452&beard_tone=7033126&blush_tone=16754890&brow_tone=11152171&eyeshadow_tone=7345154&hair_tone=65280&hair_treatment_tone=12566463&lipstick_tone=9849220&pupil_tone=7693930&skin_tone=11170379&body=0&face_proportion=7&eye_spacing=2&eye_size=0&outfit=1018474 can be display in a img tag on a site or will have legal issues with snapchat and bitmoji?

**Comment by lights0123** [comment]
@BePasquet [Snapchat says](https://www.bitmoji.com/bitmoji_brand_guidelines.pdf) on page 4 that you can't:
* Monetize Bitmoji’s brand assets or artwork
* Use Bitmoji’s brand assets or artwork as part of your marketing materials
* Sell Bitmoji merchandise
* Copy the Bitmoji look and feel
* Use Bitmoji’s brand assets or artwork in a way that suggests or implies partnership, sponsorship, or endorsement by Bitmoji or Snap Inc.
* Incorporate Bitmoji’s brand assets, artwork, or anything confusingly similar, into any other trademarks, names, domain names, usernames, or logos
* Use visual Bitmoji brand assets taken from third-party sources
* Use trademarks, names, domain names, usernames, logos, or other content that imitate or could be confused with any of the Bitmoji brand assets
* Feature Bitmoji’s brand assets in connection with pornography, illegal activities/marketplaces, or other materials that violate Bitmoji and Snap Inc.’s Terms of Service, Community Guidelines, or Privacy Policy

and on page 17:

* Use “Bitmoji,” “Bitmo,” or other confusingly similar terms in your app name, website name, domain name, or product name
* Use any of Bitmoji’s trademarks or logos or other source-identifiers (Bitmoji avatar and/or Bitmoji stickers) as part of your brand identity, which includes your app icon, logo, and product design
* Describe your app as “for Bitmoji” when it is not integrated with the Bitmoji platform or specifically designed to complement the Bitmoji app
* Use any of Bitmoji’s brand assets or artwork as your own or as part of your product and its services
* Suggest that Bitmoji sponsors or endorses your app, website, or product

Additionally, [Bitmoji Support](https://support.bitmoji.com/en-US/i-need-help) (Contact Us > I have a Media Relations question > Bitmoji's Commercial Use Policy) says that
 >You may use Bitmoji for personal or non-commercial use, subject to our [Terms of Service](https://www.bitmoji.com/support/terms.html). However, commercial use of Bitmoji (such as selling merchandise) is not permitted.

Maybe check out [Snap Kit](https://kit.snapchat.com/)? It is designed for businesses that want to include Snapchat content (including Bitmoji). You could also contact them about using Bitmoji in production, as some of the ToS hint that you may be able to use it in some capacity.

**Comment by BePasquet** [comment]
thanks a lot for the support really helpfull
