### ISSUE TITLE
Adding this to mobile application

### ISSUE THREAD

**Issue by olanipekunife** [matthewnau/libmoji#15]
Hi there

Thanks for the library

I would like to know if i can get the user **avatarID** from a mobile application(react-native- expo) so the bitmoji can look like the user instead of randomizing the features

**Thanks**

**Comment by lights0123** [comment]
@nipek This is the entire point of Snapchat's [Snap Kit](https://kit.snapchat.com/), which lets you use Snapchat features officially.
