### ISSUE TITLE
Reversing Bitmoji ID

### ISSUE THREAD

**Issue by nnastoski** [matthewnau/libmoji#4]
Hi Matthew,

Is it possible to use a Bitmoji ID to create a preview URL?

Kind regards,
Nik

**Comment by matthewnau** [comment]
Hi @nnastoski!
Unfortunately i have not discovered any ways of using a Bitmoji ID to create a preview URL. The preview engine appears to be tied to its arguments, whereas the comics engine allows for the manipulation of pre-existing user aspects. If you stay tuned, I am in the process of adding more documentation on how to manipulate the traits of pre-existing accounts to generate image URLs.

Watch for an update hopefully by the end of this week, and feel free to ask me any more questions you may have regarding Libmoji :) I will update the wiki and node package as soon as the documentation and testing is finished. (Look for version 2.1.0)

Best,
Matt
